INSERT INTO states VALUES (DEFAULT,'Alabama','AL');
INSERT INTO states VALUES (DEFAULT,'Alaska','AK');
INSERT INTO states VALUES (DEFAULT,'Arizona','AZ');
INSERT INTO states VALUES (DEFAULT,'Arkansas','AR');
INSERT INTO states VALUES (DEFAULT,'California','CA');
INSERT INTO states VALUES (DEFAULT,'Colorado','CO');
INSERT INTO states VALUES (DEFAULT,'Connecticut','CT');
INSERT INTO states VALUES (DEFAULT,'Delaware','DE');
INSERT INTO states VALUES (DEFAULT,'District Of Columbia','DC');
INSERT INTO states VALUES (DEFAULT,'Florida','FL');
INSERT INTO states VALUES (DEFAULT,'Georgia','GA');
INSERT INTO states VALUES (DEFAULT,'Hawaii','HI');
INSERT INTO states VALUES (DEFAULT,'Idaho','ID');
INSERT INTO states VALUES (DEFAULT,'Illinois','IL');
INSERT INTO states VALUES (DEFAULT,'Indiana','IN');
INSERT INTO states VALUES (DEFAULT,'Iowa','IA');
INSERT INTO states VALUES (DEFAULT,'Kansas','KS');
INSERT INTO states VALUES (DEFAULT,'Kentucky','KY');
INSERT INTO states VALUES (DEFAULT,'Louisiana','LA');
INSERT INTO states VALUES (DEFAULT,'Maine','ME');
INSERT INTO states VALUES (DEFAULT,'Maryland','MD');
INSERT INTO states VALUES (DEFAULT,'Massachusetts','MA');
INSERT INTO states VALUES (DEFAULT,'Michigan','MI');
INSERT INTO states VALUES (DEFAULT,'Minnesota','MN');
INSERT INTO states VALUES (DEFAULT,'Mississippi','MS');
INSERT INTO states VALUES (DEFAULT,'Missouri','MO');
INSERT INTO states VALUES (DEFAULT,'Montana','MT');
INSERT INTO states VALUES (DEFAULT,'Nebraska','NE');
INSERT INTO states VALUES (DEFAULT,'Nevada','NV');
INSERT INTO states VALUES (DEFAULT,'New Hampshire','NH');
INSERT INTO states VALUES (DEFAULT,'New Jersey','NJ');
INSERT INTO states VALUES (DEFAULT,'New Mexico','NM');
INSERT INTO states VALUES (DEFAULT,'New York','NY');
INSERT INTO states VALUES (DEFAULT,'North Carolina','NC');
INSERT INTO states VALUES (DEFAULT,'North Dakota','ND');
INSERT INTO states VALUES (DEFAULT,'Ohio','OH');
INSERT INTO states VALUES (DEFAULT,'Oklahoma','OK');
INSERT INTO states VALUES (DEFAULT,'Oregon','OR');
INSERT INTO states VALUES (DEFAULT,'Pennsylvania','PA');
INSERT INTO states VALUES (DEFAULT,'Rhode Island','RI');
INSERT INTO states VALUES (DEFAULT,'South Carolina','SC');
INSERT INTO states VALUES (DEFAULT,'South Dakota','SD');
INSERT INTO states VALUES (DEFAULT,'Tennessee','TN');
INSERT INTO states VALUES (DEFAULT,'Texas','TX');
INSERT INTO states VALUES (DEFAULT,'Utah','UT');
INSERT INTO states VALUES (DEFAULT,'Vermont','VT');
INSERT INTO states VALUES (DEFAULT,'Virginia','VA');
INSERT INTO states VALUES (DEFAULT,'Washington','WA');
INSERT INTO states VALUES (DEFAULT,'West Virginia','WV');
INSERT INTO states VALUES (DEFAULT,'Wisconsin','WI');
INSERT INTO states VALUES (DEFAULT,'Wyoming','WY');
INSERT INTO account_types VALUES (DEFAULT, 'Engineer');
INSERT INTO account_types VALUES (DEFAULT, 'Engineering Manager');
INSERT INTO account_types VALUES (DEFAULT, 'Engineering Firm');
INSERT INTO account_types VALUES (DEFAULT, 'Factory Engineer');
INSERT INTO account_types VALUES (DEFAULT, 'Local Representative');
INSERT INTO pressure_units VALUES (DEFAULT, 'psig');
INSERT INTO pressure_units VALUES (DEFAULT, 'psia');
INSERT INTO pressure_units VALUES (DEFAULT, 'atm g');
INSERT INTO pressure_units VALUES (DEFAULT, 'in Hg g');
INSERT INTO pressure_units VALUES (DEFAULT, 'in wc g');
INSERT INTO pressure_units VALUES (DEFAULT, 'lb/ft^2 g');
INSERT INTO pressure_units VALUES (DEFAULT, 'oz/in^2 g');
INSERT INTO pressure_units VALUES (DEFAULT, 'Torr g');
INSERT INTO temperature_units VALUES (DEFAULT, 'F');
INSERT INTO temperature_units VALUES (DEFAULT, 'C');
INSERT INTO viscosity_units VALUES (DEFAULT, 'cP');
INSERT INTO viscosity_units VALUES (DEFAULT, 'ft^2/s');
INSERT INTO viscosity_units VALUES (DEFAULT, 'in^2/s');
INSERT INTO viscosity_units VALUES (DEFAULT, 'lb/ft-s');
INSERT INTO viscosity_units VALUES (DEFAULT, 'lbf-s/ft^2');
INSERT INTO viscosity_units VALUES (DEFAULT, 'SSU');
INSERT INTO flow_capacity_units VALUES (DEFAULT, 'lb/day');
INSERT INTO flow_capacity_units VALUES (DEFAULT, 'lb/hr');
INSERT INTO flow_capacity_units VALUES (DEFAULT, 'lb/min');
INSERT INTO flow_capacity_units VALUES (DEFAULT, 'lb/s');
INSERT INTO flow_capacity_units VALUES (DEFAULT, 'BBL/d');
INSERT INTO flow_capacity_units VALUES (DEFAULT, 'BBL/h');
INSERT INTO flow_capacity_units VALUES (DEFAULT, 'ft^3/day');
INSERT INTO flow_capacity_units VALUES (DEFAULT, 'ft^3/hr');
INSERT INTO flow_capacity_units VALUES (DEFAULT, 'ft^3/min');
INSERT INTO flow_capacity_units VALUES (DEFAULT, 'GPD-Imp');
INSERT INTO flow_capacity_units VALUES (DEFAULT, 'GPD-US');
INSERT INTO flow_capacity_units VALUES (DEFAULT, 'GPH-Imp');
INSERT INTO flow_capacity_units VALUES (DEFAULT, 'GPH-US');
INSERT INTO flow_capacity_units VALUES (DEFAULT, 'GPM-Imp');
INSERT INTO flow_capacity_units VALUES (DEFAULT, 'GPM-US');
INSERT INTO flow_capacity_units VALUES (DEFAULT, 'GPS-Imp');
INSERT INTO flow_capacity_units VALUES (DEFAULT, 'GPS-US');
INSERT INTO devices VALUES (DEFAULT, 'Relief Valves');
INSERT INTO devices VALUES (DEFAULT, 'Tank Vents');
INSERT INTO devices VALUES (DEFAULT, 'Regulators');
INSERT INTO devices VALUES (DEFAULT, 'Flame Arrestors');
INSERT INTO devices VALUES (DEFAULT, 'Control Valves');
INSERT INTO devices VALUES (DEFAULT, 'Liquid Level');
INSERT INTO devices VALUES (DEFAULT, 'Pressure | Temperature Transmitters');
INSERT INTO devices VALUES (DEFAULT, 'Instrumentation Valves');

INSERT INTO media_types VALUES (DEFAULT, 'Gas', 0.650);
INSERT INTO media_types VALUES (DEFAULT, 'Steam', 0.975);
INSERT INTO media_types VALUES (DEFAULT, 'Liquid', 0.975);

INSERT INTO medias VALUES (DEFAULT, 'Air', 1.000, 28.970, null, 1.400, null);
INSERT INTO medias VALUES (DEFAULT, 'Water', null, null, 1.000, null, 1.0070);
INSERT INTO medias VALUES (DEFAULT, 'Steam', 1.000, 18.020, null, 1.310, null);


INSERT INTO sizing_basis VALUES (DEFAULT, 'Blocked Discharge', 10);
INSERT INTO sizing_basis VALUES (DEFAULT, 'Control Valve Failure', 10);
INSERT INTO sizing_basis VALUES (DEFAULT, 'Fire Case', 21);
INSERT INTO sizing_basis VALUES (DEFAULT, 'Runaway Reaction', 10);
INSERT INTO sizing_basis VALUES (DEFAULT, 'Thermal Relief', 10);
INSERT INTO sizing_basis VALUES (DEFAULT, 'Tube Rupture', 10);
INSERT INTO sizing_basis VALUES (DEFAULT, 'Valve Capacity', 10);
INSERT INTO toggle_api_asme_sizing VALUES (DEFAULT, 'API');
INSERT INTO toggle_api_asme_sizing VALUES (DEFAULT, 'ASME');
INSERT INTO orifice_sizes VALUES (DEFAULT, 'D', '0.110');
INSERT INTO orifice_sizes VALUES (DEFAULT, 'E', '0.196');
INSERT INTO orifice_sizes VALUES (DEFAULT, 'F', '0.307');
INSERT INTO orifice_sizes VALUES (DEFAULT, 'G', '0.503');
INSERT INTO orifice_sizes VALUES (DEFAULT, 'H', '0.785');
INSERT INTO orifice_sizes VALUES (DEFAULT, 'J', '1.287');
INSERT INTO orifice_sizes VALUES (DEFAULT, 'K', '1.838');
INSERT INTO orifice_sizes VALUES (DEFAULT, 'L', '2.853');
INSERT INTO orifice_sizes VALUES (DEFAULT, 'M', '3.600');
INSERT INTO orifice_sizes VALUES (DEFAULT, 'N', '4.340');
INSERT INTO orifice_sizes VALUES (DEFAULT, 'P', '6.380');
INSERT INTO orifice_sizes VALUES (DEFAULT, 'Q', '11.05');
INSERT INTO orifice_sizes VALUES (DEFAULT, 'R', '16.00');
INSERT INTO connection_sizes VALUES (DEFAULT, '1/2x3/4');
INSERT INTO connection_sizes VALUES (DEFAULT, '1/2x1');
INSERT INTO connection_sizes VALUES (DEFAULT, '3/4x3/4');
INSERT INTO connection_sizes VALUES (DEFAULT, '1x1');
INSERT INTO connection_sizes VALUES (DEFAULT, '1-1/2x1-1/2');
INSERT INTO connection_sizes VALUES (DEFAULT, '1-1/2x2');
INSERT INTO connection_sizes VALUES (DEFAULT, '1-1/2x3');
INSERT INTO connection_sizes VALUES (DEFAULT, '2x2');
INSERT INTO connection_sizes VALUES (DEFAULT, '2x3');
INSERT INTO connection_sizes VALUES (DEFAULT, '3x4');
INSERT INTO connection_sizes VALUES (DEFAULT, '4x6');
INSERT INTO connection_sizes VALUES (DEFAULT, '6x8');
INSERT INTO connection_sizes VALUES (DEFAULT, '8x10');
INSERT INTO inlet_flanges VALUES (DEFAULT, 'MNPT');
INSERT INTO inlet_flanges VALUES (DEFAULT, 'FNPT');
INSERT INTO inlet_flanges VALUES (DEFAULT, '150#');
INSERT INTO inlet_flanges VALUES (DEFAULT, '300#');
INSERT INTO inlet_flanges VALUES (DEFAULT, '600#');
INSERT INTO inlet_flanges VALUES (DEFAULT, '1500#');
INSERT INTO inlet_flanges VALUES (DEFAULT, '2500#');
INSERT INTO flange_facings VALUES (DEFAULT, 'RF');
INSERT INTO flange_facings VALUES (DEFAULT, 'RTJ');
INSERT INTO trim_types VALUES (DEFAULT, '316SS');
INSERT INTO trim_types VALUES (DEFAULT, 'Monel');
INSERT INTO trim_types VALUES (DEFAULT, 'Hastelloy C');
INSERT INTO seat_types VALUES (DEFAULT, 'Metal');
INSERT INTO seat_types VALUES (DEFAULT, 'Buna-N');
INSERT INTO seat_types VALUES (DEFAULT, 'Viton');
INSERT INTO seat_types VALUES (DEFAULT, 'EPR');
INSERT INTO seat_types VALUES (DEFAULT, 'Kalrez');
INSERT INTO seat_types VALUES (DEFAULT, 'Silicone');
INSERT INTO seat_types VALUES (DEFAULT, 'Teflon');
INSERT INTO material_variables VALUES (DEFAULT, 'Carbon Steel');
INSERT INTO material_variables VALUES (DEFAULT, '316 SS');
INSERT INTO material_variables VALUES (DEFAULT, 'Monel');
INSERT INTO material_variables VALUES (DEFAULT, 'Hastelloy C');
INSERT INTO cap_types VALUES (DEFAULT, 'screwed cap');
INSERT INTO cap_types VALUES (DEFAULT, 'standard lift lever');
INSERT INTO cap_types VALUES (DEFAULT, 'packed lift lever');
INSERT INTO cap_types VALUES (DEFAULT, 'bolted cap');
INSERT INTO project_statuses VALUES (DEFAULT, 'Open');
INSERT INTO project_statuses VALUES (DEFAULT, 'Closed');
INSERT INTO project_statuses VALUES (DEFAULT, 'Quote Needed');
INSERT INTO project_statuses VALUES (DEFAULT, 'Order');
INSERT INTO project_statuses VALUES (DEFAULT, 'Need Tracking Number');
INSERT INTO project_statuses VALUES (DEFAULT, 'Completed');
INSERT INTO tag_actions VALUES (DEFAULT, 'Technical Support');
INSERT INTO tag_actions VALUES (DEFAULT, 'Quote');
INSERT INTO tag_actions VALUES (DEFAULT, 'Status Update Needed');
INSERT INTO tag_actions VALUES (DEFAULT, 'Tracking Information');
INSERT INTO tag_actions VALUES (DEFAULT, 'Test and Repair');
INSERT INTO tag_actions VALUES (DEFAULT, 'Message');