INSERT INTO states VALUES (DEFAULT,'Alabama','AL');
INSERT INTO states VALUES (DEFAULT,'Alaska','AK');
INSERT INTO states VALUES (DEFAULT,'Arizona','AZ');
INSERT INTO states VALUES (DEFAULT,'Arkansas','AR');
INSERT INTO states VALUES (DEFAULT,'California','CA');
INSERT INTO states VALUES (DEFAULT,'Colorado','CO');
INSERT INTO states VALUES (DEFAULT,'Connecticut','CT');
INSERT INTO states VALUES (DEFAULT,'Delaware','DE');
INSERT INTO states VALUES (DEFAULT,'District Of Columbia','DC');
INSERT INTO states VALUES (DEFAULT,'Florida','FL');
INSERT INTO states VALUES (DEFAULT,'Georgia','GA');
INSERT INTO states VALUES (DEFAULT,'Hawaii','HI');
INSERT INTO states VALUES (DEFAULT,'Idaho','ID');
INSERT INTO states VALUES (DEFAULT,'Illinois','IL');
INSERT INTO states VALUES (DEFAULT,'Indiana','IN');
INSERT INTO states VALUES (DEFAULT,'Iowa','IA');
INSERT INTO states VALUES (DEFAULT,'Kansas','KS');
INSERT INTO states VALUES (DEFAULT,'Kentucky','KY');
INSERT INTO states VALUES (DEFAULT,'Louisiana','LA');
INSERT INTO states VALUES (DEFAULT,'Maine','ME');
INSERT INTO states VALUES (DEFAULT,'Maryland','MD');
INSERT INTO states VALUES (DEFAULT,'Massachusetts','MA');
INSERT INTO states VALUES (DEFAULT,'Michigan','MI');
INSERT INTO states VALUES (DEFAULT,'Minnesota','MN');
INSERT INTO states VALUES (DEFAULT,'Mississippi','MS');
INSERT INTO states VALUES (DEFAULT,'Missouri','MO');
INSERT INTO states VALUES (DEFAULT,'Montana','MT');
INSERT INTO states VALUES (DEFAULT,'Nebraska','NE');
INSERT INTO states VALUES (DEFAULT,'Nevada','NV');
INSERT INTO states VALUES (DEFAULT,'New Hampshire','NH');
INSERT INTO states VALUES (DEFAULT,'New Jersey','NJ');
INSERT INTO states VALUES (DEFAULT,'New Mexico','NM');
INSERT INTO states VALUES (DEFAULT,'New York','NY');
INSERT INTO states VALUES (DEFAULT,'North Carolina','NC');
INSERT INTO states VALUES (DEFAULT,'North Dakota','ND');
INSERT INTO states VALUES (DEFAULT,'Ohio','OH');
INSERT INTO states VALUES (DEFAULT,'Oklahoma','OK');
INSERT INTO states VALUES (DEFAULT,'Oregon','OR');
INSERT INTO states VALUES (DEFAULT,'Pennsylvania','PA');
INSERT INTO states VALUES (DEFAULT,'Rhode Island','RI');
INSERT INTO states VALUES (DEFAULT,'South Carolina','SC');
INSERT INTO states VALUES (DEFAULT,'South Dakota','SD');
INSERT INTO states VALUES (DEFAULT,'Tennessee','TN');
INSERT INTO states VALUES (DEFAULT,'Texas','TX');
INSERT INTO states VALUES (DEFAULT,'Utah','UT');
INSERT INTO states VALUES (DEFAULT,'Vermont','VT');
INSERT INTO states VALUES (DEFAULT,'Virginia','VA');
INSERT INTO states VALUES (DEFAULT,'Washington','WA');
INSERT INTO states VALUES (DEFAULT,'West Virginia','WV');
INSERT INTO states VALUES (DEFAULT,'Wisconsin','WI');
INSERT INTO states VALUES (DEFAULT,'Wyoming','WY');
INSERT INTO account_types VALUES (DEFAULT, 'Engineer');
INSERT INTO account_types VALUES (DEFAULT, 'Engineering Manager');
INSERT INTO account_types VALUES (DEFAULT, 'Engineering Firm');
INSERT INTO account_types VALUES (DEFAULT, 'Factory Engineer');
INSERT INTO account_types VALUES (DEFAULT, 'Local Representative');
INSERT INTO users VALUES (DEFAULT, 'rastalamm', 'judah', 'lamm', 'judah@lamm.com', '$2a$10$9.1XSCfZZ2vGqdrtHA1Jje.YoN.2lxZElxh8UcOCxwIM1GKglAJVa', 'new york', 'NY', '11111', 'company Name', 'president','1234567890', null, 'false', '2015-08-12 15:33:02.933-10', '2015-08-12 15:33:02.933-10' );
INSERT INTO users VALUES (DEFAULT, 'kawikaaa', 'kawika', 'kawikaLast', 'kawika@kawika.com', '$2a$10$9.1XSCfZZ2vGqdrtHA1Jje.YoN.2lxZElxh8UcOCxwIM1GKglAJVa', 'hawaii', 'HI', '12345', 'company Name', 'president','1234567890', null, 'false', '2015-08-12 15:33:02.933-10', '2015-08-12 15:33:02.933-10' );