INSERT INTO states VALUES (DEFAULT,'Alabama','AL');
INSERT INTO states VALUES (DEFAULT,'Alaska','AK');
INSERT INTO states VALUES (DEFAULT,'Arizona','AZ');
INSERT INTO states VALUES (DEFAULT,'Arkansas','AR');
INSERT INTO states VALUES (DEFAULT,'California','CA');
INSERT INTO states VALUES (DEFAULT,'Colorado','CO');
INSERT INTO states VALUES (DEFAULT,'Connecticut','CT');
INSERT INTO states VALUES (DEFAULT,'Delaware','DE');
INSERT INTO states VALUES (DEFAULT,'District Of Columbia','DC');
INSERT INTO states VALUES (DEFAULT,'Florida','FL');
INSERT INTO states VALUES (DEFAULT,'Georgia','GA');
INSERT INTO states VALUES (DEFAULT,'Hawaii','HI');
INSERT INTO states VALUES (DEFAULT,'Idaho','ID');
INSERT INTO states VALUES (DEFAULT,'Illinois','IL');
INSERT INTO states VALUES (DEFAULT,'Indiana','IN');
INSERT INTO states VALUES (DEFAULT,'Iowa','IA');
INSERT INTO states VALUES (DEFAULT,'Kansas','KS');
INSERT INTO states VALUES (DEFAULT,'Kentucky','KY');
INSERT INTO states VALUES (DEFAULT,'Louisiana','LA');
INSERT INTO states VALUES (DEFAULT,'Maine','ME');
INSERT INTO states VALUES (DEFAULT,'Maryland','MD');
INSERT INTO states VALUES (DEFAULT,'Massachusetts','MA');
INSERT INTO states VALUES (DEFAULT,'Michigan','MI');
INSERT INTO states VALUES (DEFAULT,'Minnesota','MN');
INSERT INTO states VALUES (DEFAULT,'Mississippi','MS');
INSERT INTO states VALUES (DEFAULT,'Missouri','MO');
INSERT INTO states VALUES (DEFAULT,'Montana','MT');
INSERT INTO states VALUES (DEFAULT,'Nebraska','NE');
INSERT INTO states VALUES (DEFAULT,'Nevada','NV');
INSERT INTO states VALUES (DEFAULT,'New Hampshire','NH');
INSERT INTO states VALUES (DEFAULT,'New Jersey','NJ');
INSERT INTO states VALUES (DEFAULT,'New Mexico','NM');
INSERT INTO states VALUES (DEFAULT,'New York','NY');
INSERT INTO states VALUES (DEFAULT,'North Carolina','NC');
INSERT INTO states VALUES (DEFAULT,'North Dakota','ND');
INSERT INTO states VALUES (DEFAULT,'Ohio','OH');
INSERT INTO states VALUES (DEFAULT,'Oklahoma','OK');
INSERT INTO states VALUES (DEFAULT,'Oregon','OR');
INSERT INTO states VALUES (DEFAULT,'Pennsylvania','PA');
INSERT INTO states VALUES (DEFAULT,'Rhode Island','RI');
INSERT INTO states VALUES (DEFAULT,'South Carolina','SC');
INSERT INTO states VALUES (DEFAULT,'South Dakota','SD');
INSERT INTO states VALUES (DEFAULT,'Tennessee','TN');
INSERT INTO states VALUES (DEFAULT,'Texas','TX');
INSERT INTO states VALUES (DEFAULT,'Utah','UT');
INSERT INTO states VALUES (DEFAULT,'Vermont','VT');
INSERT INTO states VALUES (DEFAULT,'Virginia','VA');
INSERT INTO states VALUES (DEFAULT,'Washington','WA');
INSERT INTO states VALUES (DEFAULT,'West Virginia','WV');
INSERT INTO states VALUES (DEFAULT,'Wisconsin','WI');
INSERT INTO states VALUES (DEFAULT,'Wyoming','WY');
INSERT INTO account_types VALUES (DEFAULT, 'Engineer');
INSERT INTO account_types VALUES (DEFAULT, 'Engineering Manager');
INSERT INTO account_types VALUES (DEFAULT, 'Engineering Firm');
INSERT INTO account_types VALUES (DEFAULT, 'Factory Engineer');
INSERT INTO account_types VALUES (DEFAULT, 'Local Representative');
INSERT INTO pressure_units VALUES (DEFAULT, 'psig');
INSERT INTO pressure_units VALUES (DEFAULT, 'psia');
INSERT INTO pressure_units VALUES (DEFAULT, 'atm g');
INSERT INTO pressure_units VALUES (DEFAULT, 'in Hg g');
INSERT INTO pressure_units VALUES (DEFAULT, 'in wc g');
INSERT INTO pressure_units VALUES (DEFAULT, 'lb/ft^2 g');
INSERT INTO pressure_units VALUES (DEFAULT, 'oz/in^2 g');
INSERT INTO pressure_units VALUES (DEFAULT, 'Torr g');
INSERT INTO temperature_units VALUES (DEFAULT, 'F');
INSERT INTO temperature_units VALUES (DEFAULT, 'C');
INSERT INTO viscosity_units VALUES (DEFAULT, 'cP');
INSERT INTO viscosity_units VALUES (DEFAULT, 'ft^2/s');
INSERT INTO viscosity_units VALUES (DEFAULT, 'in^2/s');
INSERT INTO viscosity_units VALUES (DEFAULT, 'lb/ft-s');
INSERT INTO viscosity_units VALUES (DEFAULT, 'lbf-s/ft^2');
INSERT INTO viscosity_units VALUES (DEFAULT, 'SSU');
INSERT INTO flow_capacity_units VALUES (DEFAULT, 'lb/day');
INSERT INTO flow_capacity_units VALUES (DEFAULT, 'lb/hr');
INSERT INTO flow_capacity_units VALUES (DEFAULT, 'lb/min');
INSERT INTO flow_capacity_units VALUES (DEFAULT, 'lb/s');
INSERT INTO flow_capacity_units VALUES (DEFAULT, 'BBL/d');
INSERT INTO flow_capacity_units VALUES (DEFAULT, 'BBL/h');
INSERT INTO flow_capacity_units VALUES (DEFAULT, 'ft^3/day');
INSERT INTO flow_capacity_units VALUES (DEFAULT, 'ft^3/hr');
INSERT INTO flow_capacity_units VALUES (DEFAULT, 'ft^3/min');
INSERT INTO flow_capacity_units VALUES (DEFAULT, 'GPD-Imp');
INSERT INTO flow_capacity_units VALUES (DEFAULT, 'GPD-US');
INSERT INTO flow_capacity_units VALUES (DEFAULT, 'GPH-Imp');
INSERT INTO flow_capacity_units VALUES (DEFAULT, 'GPH-US');
INSERT INTO flow_capacity_units VALUES (DEFAULT, 'GPM-Imp');
INSERT INTO flow_capacity_units VALUES (DEFAULT, 'GPM-US');
INSERT INTO flow_capacity_units VALUES (DEFAULT, 'GPS-Imp');
INSERT INTO flow_capacity_units VALUES (DEFAULT, 'GPS-US');
INSERT INTO devices VALUES (DEFAULT, 'Relief Valves');
INSERT INTO devices VALUES (DEFAULT, 'Tank Vents');
INSERT INTO devices VALUES (DEFAULT, 'Regulators');
INSERT INTO devices VALUES (DEFAULT, 'Flame Arrestors');
INSERT INTO devices VALUES (DEFAULT, 'Control Valves');
INSERT INTO devices VALUES (DEFAULT, 'Liquid Level');
INSERT INTO devices VALUES (DEFAULT, 'Pressure | Temperature Transmitters');
INSERT INTO devices VALUES (DEFAULT, 'Instrumentation Valves');
INSERT INTO media_types VALUES (DEFAULT, 'Gas', 0.650);
INSERT INTO media_types VALUES (DEFAULT, 'Steam', 0.975);
INSERT INTO media_types VALUES (DEFAULT, 'Liquid', 0.975);
INSERT INTO medias VALUES (DEFAULT, 'Acetaldehyde', 0.779, 0.23800);
INSERT INTO medias VALUES (DEFAULT, 'Acetic Acid', 1.051, 1.22000);
INSERT INTO medias VALUES (DEFAULT, 'Acetone', 0.792, 0.3200);
INSERT INTO medias VALUES (DEFAULT, 'Ammonia', 0.666, 0.2);
INSERT INTO medias VALUES (DEFAULT, 'Aniline', 1.021, 3.7100);
INSERT INTO medias VALUES (DEFAULT, 'Beer', 1.010, 1.818);
INSERT INTO medias VALUES (DEFAULT, 'Benzene', 0.880, 0.60400);
INSERT INTO medias VALUES (DEFAULT, 'Boiler Feed Water', 1.000, 1.0070);
INSERT INTO medias VALUES (DEFAULT, 'Boron Trifluoride', 1.570, 1.800);
INSERT INTO medias VALUES (DEFAULT, 'Butadiene', 0.622, 0.2500);
INSERT INTO medias VALUES (DEFAULT, 'Butane-N', 0.579, 0.2580);
INSERT INTO medias VALUES (DEFAULT, 'Butylene', 0.600, 2.4000);
INSERT INTO medias VALUES (DEFAULT, 'Carbon Dioxide', 1.030, 0.108);
INSERT INTO medias VALUES (DEFAULT, 'Carbon Disulfide', 1.270, 0.419);
INSERT INTO medias VALUES (DEFAULT, 'Carbon Tetrachloride', 1.600, 0.901);
INSERT INTO medias VALUES (DEFAULT, 'Chlorine', 1.420, 0.3500);
INSERT INTO medias VALUES (DEFAULT, 'Condensate', 0.718, 0.74500);
INSERT INTO medias VALUES (DEFAULT, 'Crude Oil, Heavy', 0.862, 136.000);
INSERT INTO medias VALUES (DEFAULT, 'Crude Oil, Light', 0.790, 8.000);
INSERT INTO medias VALUES (DEFAULT, 'Cyclohexane', 0.780, 1.0200);
INSERT INTO medias VALUES (DEFAULT, 'Cyclopropane', 0.621, 1.0200);
INSERT INTO medias VALUES (DEFAULT, 'Decane-n', 0.731, 1.725);
INSERT INTO medias VALUES (DEFAULT, 'Diesel', 0.885, 3.5400);
INSERT INTO medias VALUES (DEFAULT, 'Diethyl Ether', 2.570, 1.000);
INSERT INTO medias VALUES (DEFAULT, 'Ethylene Glycol', 1.120, 21.000);
INSERT INTO medias VALUES (DEFAULT, 'Dimethyl Ether', 0.663, 0.224);
INSERT INTO medias VALUES (DEFAULT, 'Dimenthylamine', 0.656, 1.000);
INSERT INTO medias VALUES (DEFAULT, 'Ethane', 0.356, 1.000);
INSERT INTO medias VALUES (DEFAULT, 'Ethanol', 0.790, 1.0740);
INSERT INTO medias VALUES (DEFAULT, 'Ethylene Glycol', 1.115, 21.000);
INSERT INTO medias VALUES (DEFAULT, 'Fuel Oil', 0.885, 3.788);
INSERT INTO medias VALUES (DEFAULT, 'Gasoline', 0.740, 0.65100);
INSERT INTO medias VALUES (DEFAULT, 'Glycerin', 1.260, 816.00);
INSERT INTO medias VALUES (DEFAULT, 'Heptane', 0.685, 0.3600);
INSERT INTO medias VALUES (DEFAULT, 'Hexane', 0.660, 0.29400);
INSERT INTO medias VALUES (DEFAULT, 'Hydrochloric Acid', 1.640, 1.900);
INSERT INTO medias VALUES (DEFAULT, 'Hydrogen Sulfide', 0.780, 1.00);
INSERT INTO medias VALUES (DEFAULT, 'Isobutane', 0.558, 0.27700);
INSERT INTO medias VALUES (DEFAULT, 'Isoprene', 0.682, 1.000);
INSERT INTO medias VALUES (DEFAULT, 'Isopropanol', 0.786, 1.000);
INSERT INTO medias VALUES (DEFAULT, 'Jet Fuel', 0.820, 6.4780);
INSERT INTO medias VALUES (DEFAULT, 'Kerosene', 0.820, 2.2220);
INSERT INTO medias VALUES (DEFAULT, 'Methane', 0.300, 1.000);
INSERT INTO medias VALUES (DEFAULT, 'Methanol', 0.792, 0.54400);
INSERT INTO medias VALUES (DEFAULT, 'Methyl Chloride', 0.921, 1.000);
INSERT INTO medias VALUES (DEFAULT, 'Methyl Mercaptan', 0.870, 1.000);
INSERT INTO medias VALUES (DEFAULT, 'Ethylene Glycol', 1.115, 21.000);
INSERT INTO medias VALUES (DEFAULT, 'Monomethylamine', 0.663, 1.000);
INSERT INTO medias VALUES (DEFAULT, 'Motor Oil', 0.940, 8.700);
INSERT INTO medias VALUES (DEFAULT, 'Naphtha', 0.665, 7.11900);
INSERT INTO medias VALUES (DEFAULT, 'Nitric Acid', 1.500, 1.000);
INSERT INTO medias VALUES (DEFAULT, 'Nitrogen', 0.809, 1.000);
INSERT INTO medias VALUES (DEFAULT, 'Nitrous Oxide', 1.230, 1.000);
INSERT INTO medias VALUES (DEFAULT, 'Octane', 0.703, 0.8900);
INSERT INTO medias VALUES (DEFAULT, 'Oxygen', 1.140, 0.196);
INSERT INTO medias VALUES (DEFAULT, 'Pentane', 0.627, 0.3400);
INSERT INTO medias VALUES (DEFAULT, 'Propadiene', 0.659, 1.000);
INSERT INTO medias VALUES (DEFAULT, 'Propane', 0.501, 0.18600);
INSERT INTO medias VALUES (DEFAULT, 'Propylene', 0.514, 1.000);
INSERT INTO medias VALUES (DEFAULT, 'Propylene Oxide', 0.830, 1.000);
INSERT INTO medias VALUES (DEFAULT, 'Sea Water', 1.025, 1.179);
INSERT INTO medias VALUES (DEFAULT, 'Styrene', 0.908, 1.000);
INSERT INTO medias VALUES (DEFAULT, 'Sulfur Dioxide', 1.430, 0.36800);
INSERT INTO medias VALUES (DEFAULT, 'Sulfur Hexafluoride', 1.370, 1.000);
INSERT INTO medias VALUES (DEFAULT, 'Sulfuric Acid (20%)', 1.140, 1.200);
INSERT INTO medias VALUES (DEFAULT, 'Sulfuric Acid (60%)', 1.500, 6.600);
INSERT INTO medias VALUES (DEFAULT, 'Sulfuric Acid (95-100%)', 1.839, 26.800);
INSERT INTO medias VALUES (DEFAULT, 'Toluene', 0.868, 0.5900);
INSERT INTO medias VALUES (DEFAULT, 'Triethylamine', 0.728, 0.36300);
INSERT INTO medias VALUES (DEFAULT, 'Triethylene Glycol', 1.126, 45.000);
INSERT INTO medias VALUES (DEFAULT, 'Vinyl Chloride Monomer', 0.985, 1.000);
INSERT INTO medias VALUES (DEFAULT, 'Water', 1.000, 1.00700);
INSERT INTO medias VALUES (DEFAULT, 'Water Other', 1.000, 1.00700);
INSERT INTO medias VALUES (DEFAULT, 'Xylene', 0.862, 0.81200);
INSERT INTO sizing_basis VALUES (DEFAULT, 'Blocked Discharge', 10);
INSERT INTO sizing_basis VALUES (DEFAULT, 'Control Valve Failure', 10);
INSERT INTO sizing_basis VALUES (DEFAULT, 'Fire Case', 21);
INSERT INTO sizing_basis VALUES (DEFAULT, 'Runaway Reaction', 10);
INSERT INTO sizing_basis VALUES (DEFAULT, 'Thermal Relief', 10);
INSERT INTO sizing_basis VALUES (DEFAULT, 'Tube Rupture', 10);
INSERT INTO sizing_basis VALUES (DEFAULT, 'Valve Capacity', 10);
INSERT INTO toggle_api_asme_sizing VALUES (DEFAULT, 'API');
INSERT INTO toggle_api_asme_sizing VALUES (DEFAULT, 'ASME');
INSERT INTO orifice_sizes VALUES (DEFAULT, 'D', '0.110');
INSERT INTO orifice_sizes VALUES (DEFAULT, 'E', '0.196');
INSERT INTO orifice_sizes VALUES (DEFAULT, 'F', '0.307');
INSERT INTO orifice_sizes VALUES (DEFAULT, 'G', '0.503');
INSERT INTO orifice_sizes VALUES (DEFAULT, 'H', '0.785');
INSERT INTO orifice_sizes VALUES (DEFAULT, 'J', '1.287');
INSERT INTO orifice_sizes VALUES (DEFAULT, 'K', '1.838');
INSERT INTO orifice_sizes VALUES (DEFAULT, 'L', '2.853');
INSERT INTO orifice_sizes VALUES (DEFAULT, 'M', '3.600');
INSERT INTO orifice_sizes VALUES (DEFAULT, 'N', '4.340');
INSERT INTO orifice_sizes VALUES (DEFAULT, 'P', '6.380');
INSERT INTO orifice_sizes VALUES (DEFAULT, 'Q', '11.05');
INSERT INTO orifice_sizes VALUES (DEFAULT, 'R', '16.00');
INSERT INTO connection_sizes VALUES (DEFAULT, '1/2x3/4');
INSERT INTO connection_sizes VALUES (DEFAULT, '1/2x1');
INSERT INTO connection_sizes VALUES (DEFAULT, '3/4x3/4');
INSERT INTO connection_sizes VALUES (DEFAULT, '1x1');
INSERT INTO connection_sizes VALUES (DEFAULT, '1-1/2x1-1/2');
INSERT INTO connection_sizes VALUES (DEFAULT, '1-1/2x2');
INSERT INTO connection_sizes VALUES (DEFAULT, '1-1/2x3');
INSERT INTO connection_sizes VALUES (DEFAULT, '2x2');
INSERT INTO connection_sizes VALUES (DEFAULT, '2x3');
INSERT INTO connection_sizes VALUES (DEFAULT, '3x4');
INSERT INTO connection_sizes VALUES (DEFAULT, '4x6');
INSERT INTO connection_sizes VALUES (DEFAULT, '6x8');
INSERT INTO connection_sizes VALUES (DEFAULT, '8x10');
INSERT INTO inlet_flanges VALUES (DEFAULT, 'MNPT');
INSERT INTO inlet_flanges VALUES (DEFAULT, 'FNPT');
INSERT INTO inlet_flanges VALUES (DEFAULT, '150#');
INSERT INTO inlet_flanges VALUES (DEFAULT, '300#');
INSERT INTO inlet_flanges VALUES (DEFAULT, '600#');
INSERT INTO inlet_flanges VALUES (DEFAULT, '1500#');
INSERT INTO inlet_flanges VALUES (DEFAULT, '2500#');
INSERT INTO flange_facings VALUES (DEFAULT, 'RF');
INSERT INTO flange_facings VALUES (DEFAULT, 'RTJ');
INSERT INTO trim_types VALUES (DEFAULT, '316SS');
INSERT INTO trim_types VALUES (DEFAULT, 'Monel');
INSERT INTO trim_types VALUES (DEFAULT, 'Hastelloy C');
INSERT INTO seat_types VALUES (DEFAULT, 'Metal');
INSERT INTO seat_types VALUES (DEFAULT, 'Buna-N');
INSERT INTO seat_types VALUES (DEFAULT, 'Viton');
INSERT INTO seat_types VALUES (DEFAULT, 'EPR');
INSERT INTO seat_types VALUES (DEFAULT, 'Kalrez');
INSERT INTO seat_types VALUES (DEFAULT, 'Silicone');
INSERT INTO seat_types VALUES (DEFAULT, 'Teflon');
INSERT INTO material_variables VALUES (DEFAULT, 'Carbon Steel');
INSERT INTO material_variables VALUES (DEFAULT, '316 SS');
INSERT INTO material_variables VALUES (DEFAULT, 'Monel');
INSERT INTO material_variables VALUES (DEFAULT, 'Hastelloy C');
INSERT INTO cap_types VALUES (DEFAULT, 'screwed cap');
INSERT INTO cap_types VALUES (DEFAULT, 'standard lift lever');
INSERT INTO cap_types VALUES (DEFAULT, 'packed lift lever');
INSERT INTO cap_types VALUES (DEFAULT, 'bolted cap');
INSERT INTO project_statuses VALUES (DEFAULT, 'Open');
INSERT INTO project_statuses VALUES (DEFAULT, 'Closed');
INSERT INTO project_statuses VALUES (DEFAULT, 'Quote Needed');
INSERT INTO project_statuses VALUES (DEFAULT, 'Order');
INSERT INTO project_statuses VALUES (DEFAULT, 'Need Tracking Number');
INSERT INTO project_statuses VALUES (DEFAULT, 'Completed');
INSERT INTO tag_actions VALUES (DEFAULT, 'Technical Support');
INSERT INTO tag_actions VALUES (DEFAULT, 'Quote');
INSERT INTO tag_actions VALUES (DEFAULT, 'Status Update Needed');
INSERT INTO tag_actions VALUES (DEFAULT, 'Tracking Information');
INSERT INTO tag_actions VALUES (DEFAULT, 'Test and Repair');
INSERT INTO tag_actions VALUES (DEFAULT, 'Message');